#!/usr/bin/env python3
"""async_comprehension module
"""

from typing import List

# Import the async_generator function from the previous file
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Collects 10 random float numbers using async comprehension.

    Returns:
        List[float]: List containing 10 float numbers generated by async_generator.
    """
    return [n async for n in async_generator()]
