#!/usr/bin/env python3
"""async_comprehension module

Defines a coroutine that collects 10 random numbers
generated by async_generator using async comprehension.
"""

from typing import List
from 0-async_generator import async_generator  # or: from . import async_generator (if same folder)

async def async_comprehension() -> List[float]:
    """
    Collects 10 random float numbers using async comprehension.

    Returns:
        List[float]: List containing 10 randomly generated float numbers.
    """
    return [i async for i in async_generator()]
